@startuml
interface Function {

}
abstract class TerminalExpression implements Function {}
class Variable implements TerminalExpression {}
class Literal implements TerminalExpression {}
abstract class NonTerminalExpression implements Function {
    evaluateRight() : Function
    evaluateLeft(): Function
    getVariablesList(): List<String>
}
class Sum implements NonTerminalExpression{}
class Difference implements NonTerminalExpression{}
class Product implements NonTerminalExpression{}
class Divide implements NonTerminalExpression{}
class Equals implements NonTerminalExpression{}

NonTerminalExpression --> Function
@enduml